import { useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import User from './components/User'
import students from './data/six.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const modalRef = useRef<HTMLDivElement>(null)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div ref={modalRef} className={styles.modal}>
          <div className={styles.modalContent}>
            <h1>외출하시겠습니까?</h1>
            <p>외출 사유를 선택해주세요.</p>
          </div>
        </div>
        <nav>
          
        </nav>
        <section className={styles.container}>
          <h1 className={styles.title}>1학년 6반</h1>
          <section className={styles.cards}>
            {students.map((student) => {
              if (student.number % 4 === 0) return <User name={`${student.number} ${student.name}`} isExit={true} modal={modalRef}></User>
              else return <User name={`${student.number} ${student.name}`} isExit={false} modal={modalRef}></User>
            })}
          </section>
        </section>
        
      </main>
    </>
  )
}
